//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAirlineReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public string FlightNo { get; set; }
        public int TicketNo { get; set; }
        public string DepartureCity { get; set; }
        public string ArrivalCity { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int PassengerId { get; set; }
        public string Cabin { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int RegistrationId { get; set; }
        public string FlightStatus { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
